### ISSUE TITLE
'AudioVisualizationView' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by guoyingtao** [bastienFalcou/SoundWave#17]
The error occurred when I tried to initialize the view like below
AudioVisualizationView(frame: CGRect(x: 0.0, y: 0.0, width: 300.0, height: 500.0)))

**Comment by msjt13** [comment]
any solution of this ?

**Comment by OurBigAdventure** [comment]
The two solutions I found were to create the AudioVisualizationView in IB or to just initialize it with AudioVisualizationView() then set the frame.

**Comment by bastienFalcou** [comment]
@guoyingtao @msjt13 @OurBigAdventure, thank you guys for raising that point, I have just fixed that and it will be in the next version of the Pod!
