### ISSUE TITLE
Audio Visualization View not displayed if it's inside UITable Cell

### ISSUE THREAD

**Issue by Ashraf90909** [bastienFalcou/SoundWave#21]
hi ,
I tried to add Audio Visualization View inside cell in UITable view when did selected row is triggered the Audio sound played correctly but the Audio Visualization View does not display any chart its keeps blank

here is my code : -

  override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cell = tableView.dequeueReusableCell(withIdentifier: "AudioCellidentifier", for: indexPath as IndexPath) as! AudioCell
        let audio = audioFiles![indexPath.row]
        let metringLevels = audio.MetringLevels.sorted(byKeyPath: "order", ascending : true)
        var metrLevel :[Float] = []
        for ( metringLevel )  in metringLevels {
            metrLevel.append(metringLevel.level)
        }
        let fileUrl = NSURL(string: audio.fileUrl)! as URL
          do {
            viewModel.currentAudioRecord = SoundRecord(audioFilePathLocal: fileUrl , meteringLevels: metrLevel)
            let duration = try self.viewModel.startPlaying()
            cell.audioVisualizationView.audioVisualizationMode = .read
            cell.audioVisualizationView.meteringLevels = metrLevel
            cell.audioVisualizationView.play(for: duration)
        } catch {
            self.showAlert(with: error)
        }
       tableView.deselectRow(at: indexPath, animated: true)
    }

any suggestion ?

**Comment by Ashraf90909** [comment]
i figure out the issues insted of using this line of code
let cell = tableView.dequeueReusableCell(withIdentifier: "AudioCellidentifier", for: indexPath as 
I replace the code with 
 let cell = tableView.cellForRow(at: indexPath) as! AudioCell 
now it's works just fine

**Comment by Ahmed-Elshobary** [comment]
Hello Ashraf 
are you represented in in the cell ?
i tried to show it on every cell but it not appeared
