### ISSUE TITLE
iOS 12 SDK

### ISSUE THREAD

**Issue by sshnip** [bastienFalcou/SoundWave#26]
Hi
Could you please fix `RunLoopMode.defaultRunLoopMode` in Chronometer.swift to resolve compilation errors
Thanks

**Comment by bastienFalcou** [comment]
@sshnip @pLembo90 I just merged [this Pull Request](https://github.com/bastienFalcou/SoundWave/pull/27) introducing iOS 12 support 👌 This will be in the next version of the Pod I am going to release later today!
