### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by donpironet** [bastienFalcou/SoundWave#33]
When I run the example project it doesn't do anything. I start talking but it doesn't display anything.

**Comment by turk-jk** [comment]
I confirm, neither on my app when I follow the instructions

**Comment by bastienFalcou** [comment]
@donpironet @turk-jk thank you for reporting that! I will investigate this and make sure the example project works as expected 👍

**Comment by bastienFalcou** [comment]
@donpironet @turk-jk sorry for the delay, I just tested the Example app and everything seemed to work fine (see below) 😊 

You guys tried it on your phone right? Note that it would indeed not work on Simulator.

![Demo](https://user-images.githubusercontent.com/16304947/56475569-f95c0300-6457-11e9-8863-b9011695a1ad.gif)

**Comment by hoangnam714** [comment]
@bastienFalcou oh no, i tried to run it on real device but it keeps stopping and not working
