### ISSUE TITLE
How can I remove white lines in the middle of a level meter?

### ISSUE THREAD

**Issue by HanSJin** [bastienFalcou/SoundWave#40]
Hi. @bastienFalcou I have a question :) ..
How can I remove white lines in the middle of a level meter?
The sample what I want as follows.

<img width="257" alt="스크린샷 2019-06-11 오후 9 46 21" src="https://user-images.githubusercontent.com/13335632/59273090-5f177f00-8c92-11e9-8d76-2166c833481f.png">

Thank you for your answer 👍

**Comment by bastienFalcou** [comment]
Hi @HanSJin! Unfortunately this is not something we currently support, although it can be added in a future Pull Request as part of the customization. I can try to address that in the coming days! Otherwise feel free to open a Pull Request if you get there earlier 😊

**Comment by HanSJin** [comment]
Thank you for your answer 🙂
I founded that the cornerRadius was applied both up and down in the UpperBar/LowerBar.
So, what I'm curious about is, is there a reason why you split the level meter into upper/lower bars?

**Comment by HanSJin** [comment]
```
barPath = UIBezierPath(roundedRect: CGRect(x: xPointForMeteringLevel,
                                           y: self.centerY - heightForMeteringLevel,
                                           width: self.meteringLevelBarWidth,
                                            height: heightForMeteringLevel * 2),
                       cornerRadius: self.meteringLevelBarCornerRadius)
```
Likes above codes,
If the distinguisho of upper/lower division is removed and the bar is drawn with one BezierPath, the middle division line disappears.
If there is no special issue with the division line, I will create a PR that can adjust it to be an option.

**Comment by bastienFalcou** [comment]
Hi @HanSJin, my apologies for the delay answering! 

The reason for this splitting in two upper/lower bars was purely due to design directions I initially had to follow for a project. We can totally inject an option that gives the choice to the user.

I saw that you opened a Pull Request, fantastic I am going to review it. Thank you so much for your contribution! 💪
