### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by nabeelhayat** [bastienFalcou/SoundWave#45]
Could we change the speed of the wave according to when i change the rate(speed) of the Audio?

**Comment by bastienFalcou** [comment]
Hi @NabeelHayat, technically if you know then how long the remaining of the audio to play will last, you could call the following function with this appropriate number:

```swift
let timeRaminingForAudioInFastMode = <calculation>
self.audioVisualizationView.play(for: timeRaminingForAudioInFastMode)
```

Would that work for you?

**Comment by nabeelhayat** [comment]
Thanks, it's working for me.
